# Generated by Django 2.2.5 on 2020-04-29 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sample',
        ),
    ]
