# Generated by Django 2.2.5 on 2020-04-29 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('article', '0002_delete_sample'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('article_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('article_url', models.CharField(max_length=100)),
                ('article_category', models.CharField(max_length=50)),
                ('article_media', models.CharField(max_length=50)),
                ('article_date', models.CharField(max_length=20)),
                ('article_title', models.CharField(max_length=200)),
                ('article_content', models.TextField()),
            ],
        ),
    ]
