# Generated by Django 2.2.5 on 2020-04-29 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_sample'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sample',
            new_name='Article',
        ),
    ]
