# Generated by Django 2.2.5 on 2020-04-29 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20200429_1916'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
